basePath: /v1
definitions:
  main.runRequest:
    properties:
      code:
        type: string
      immudb:
        items:
          type: integer
        type: array
    type: object
  main.runResponse:
    properties:
      immudb:
        items:
          type: integer
        type: array
      stderr:
        type: string
      stdout:
        type: string
      tree:
        items:
          type: integer
        type: array
    type: object
  main.versionInfo:
    properties:
      buildtime:
        type: string
      version:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a PoC playground rest server
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://codenotary.com/terms
  title: Playground REST server
  version: "1.0"
paths:
  /exec/run:
    post:
      consumes:
      - application/json
      operationId: runCode
      parameters:
      - description: Run request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/main.runRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.runResponse'
        "400":
          description: ""
        "500":
          description: ""
      summary: Show software version
      tags:
      - info
  /info/version:
    get:
      operationId: showVersion
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.versionInfo'
      summary: Show software version
      tags:
      - info
swagger: "2.0"
