basePath: /api/v1
definitions:
  main.OutputLine:
    properties:
      flux:
        type: string
      line:
        type: string
      timestamp:
        type: number
      token:
        items:
          type: integer
        type: array
      tree:
        items:
          type: integer
        type: array
      verified:
        type: boolean
    type: object
  main.listrunnerResponse:
    properties:
      ids:
        items:
          type: string
        type: array
    type: object
  main.runLog:
    properties:
      lines:
        items:
          $ref: '#/definitions/main.runLogLine'
        type: array
      size:
        type: integer
    type: object
  main.runLogLine:
    properties:
      container:
        type: string
      label:
        type: string
      logentry:
        type: string
      timestamp:
        type: number
    type: object
  main.runRequest:
    properties:
      code:
        type: string
      immudb:
        items:
          type: integer
        type: array
      token:
        items:
          type: integer
        type: array
    type: object
  main.runResponse:
    properties:
      immudb:
        items:
          type: integer
        type: array
      output:
        items:
          $ref: '#/definitions/main.OutputLine'
        type: array
      token:
        items:
          type: integer
        type: array
      tree:
        items:
          type: integer
        type: array
      verified:
        type: boolean
    type: object
  main.runnerResponse:
    properties:
      error:
        type: string
      id:
        type: string
      status:
        type: string
    type: object
  main.versionInfo:
    properties:
      buildtime:
        type: string
      version:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a PoC playground rest server
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://codenotary.com/terms
  title: Playground REST server
  version: "1.0"
paths:
  /exec/logs:
    get:
      operationId: execLog
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.runLog'
      summary: Return last 16 container run logs
      tags:
      - player
  /exec/python:
    post:
      consumes:
      - application/json
      operationId: pythonExec
      parameters:
      - description: Run request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/main.runRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.runResponse'
        "400":
          description: ""
        "500":
          description: ""
      summary: Execute a python script
      tags:
      - player
  /info/version:
    get:
      operationId: showVersion
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.versionInfo'
      summary: Show software version
      tags:
      - info
  /run/close/{id}:
    post:
      operationId: closeRunner
      parameters:
      - description: Container id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.runnerResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.runnerResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.runnerResponse'
      summary: Halts and delete an interactive container
      tags:
      - runner
  /run/list:
    get:
      operationId: listRunners
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.listrunnerResponse'
        "400":
          description: ""
        "500":
          description: ""
      summary: List containers ids of running containers for interactive ouse
      tags:
      - runner
  /run/new:
    post:
      operationId: newRunner
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.runnerResponse'
        "400":
          description: ""
        "500":
          description: ""
      summary: Launch a new container for interactive use
      tags:
      - runner
swagger: "2.0"
